---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2019/9/18 23:25
---

--- 漏斗标识
local funnelKey = KEYS[1]
--- 动作标识
local action = ARGV[1]

--- 初始化
--- @param funnelKey 漏斗标识
--- @param capacity 漏斗容量
--- @param leakingRate 漏斗漏水最大速率
--- @param leakingTime 上次漏水完毕的结束时间
local function init(funnelKey, capacity, leakingRate, leftQuota, leakingTime)
    local funnelInfo = redis.pcall("HMGET", funnelKey, "capacity", "leakingRate")
    local orgCapacity = tonumber(funnelInfo[1])
    local orgLeakingRate = tonumber(funnelInfo[2])

    if (nil == orgCapacity) or (nil == orgLeakingRate) or (capacity ~= orgCapacity) or (leakingRate ~= orgLeakingRate) then
        redis.pcall("HMSET", funnelKey, "capacity", capacity, "leakingRate", leakingRate, "leftQuota", leftQuota, "leakingTime", leakingTime)
    end
    return 1;
end


--- 删除漏斗
local function delete(funnelKey)
    redis.pcall("DEL", funnelKey)
    return 1;
end

if method == 'init' then
    return init(key, ARGV[2], ARGV[3], ARGV[4])
elseif method == 'delete' then
    return delete(key)
else
    --ignore
end